# Generated by Django 5.0.1 on 2024-01-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
